version: '3'

services:
 
  mysqldb:
    image: mysql/mysql-server:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      
     - MYSQL_DATABASE=cardschemedb
     - MYSQL_USER=root
     - MYSQL_PASSWORD=password
     
    volumes:
          
      - /data/mysql

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
      
  kafka:
    image: wurstmeister/kafka:1.0.0
    restart: always
    ports:
       - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka

  cardscheme:
    image: austine234/cardscheme
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    restart: always
    depends_on:
      - mysqldb
      - zookeeper
      - kafka
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysqldb:3306/cardschemedb'
      SPRING_PROFILES_ACTIVE: 'mysql'
     
      KAFKA_ADVERTISED_LISTENERS: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: 2181
      
  
  